name: Deploy to Firebase
on:
  push:
    branches:
      - main
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Increment Version Number
        run: node ./scripts/increment-version.js
      
      - name: Generate Version File
        run: node ./scripts/generate-version.js
      
      - name: Build
        run: npm run build
        env:
          CI: false
          
      - name: Verify Build Output
        run: |
          echo "Verifying build output..."
          if [ ! -d "dist" ]; then
            echo "Error: dist directory not found!"
            exit 1
          fi
          if [ ! -f "dist/index.html" ]; then
            echo "Error: index.html not found in dist directory!"
            exit 1
          fi
          echo "Build output verified successfully."

      - name: Install Firebase Tools
        run: npm install -g firebase-tools@12.9.1
        
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_FIREWORK_FACTORY }}'
          channelId: live
          projectId: firework-factory
